language: python
python:
    - "3.6"
    - "3.5"
    - "2.7"
    - "pypy"
    - "pypy3"

install: "pip install -e .[test]"
script: make test
before_install:
    - pip install codecov
after_success:
    - codecov
notifications:
    slack: raspberrypifoundation:YoIHtVdg8Hd6gcA09QEmCYXN
